# Site settings
title: Frank Selensky blog
email: 
description: "Blockchain stuff"
baseurl: ""
url: "http://viking-frank.github.io"
github_username:  viking-frank

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
